# Dependencies
imarkdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            jyt0532's Blog
tagline:          'Simple Made Easy'
description:      'Learning never ends'
url:              https://www.jyt0532.com
baseurl:          https://www.jyt0532.com/

author:
  name:           'BoYu'
  url:            https://twitter.com/jyt0532

paginate:         5

# Custom vars
version:          2.1.0
plugins_dir:
        - jekyll-paginate
        - jekyll-gist

gems: [jekyll-paginate,jekyll-gist,jekyll-twitter-plugin]

plugins: [jekyll-paginate,jekyll-gist,jekyll-twitter-plugin]

github:
  repo:           https://github.com/jyt0532

algolia:
  application_id: CBY2UML8Z2
  index_name: jyt0532_0408
  search_only_api_key: 66f08de38e8558a80afd764c6d59f028
