# Dependencies
imarkdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            jyt0532's Blog
tagline:          'Simple Made Easy'
description:      'learning never ends'
url:              https://jyt0532.github.io
baseurl:          /

author:
  name:           'BoYu'
  url:            https://twitter.com/jyt0532

paginate:         5

# Custom vars
version:          2.1.0
plugins:
        - jekyll-paginate
        - jekyll-gist

github:
  repo:           https://github.com/jyt0532

algolia:
  application_id: CBY2UML8Z2
  index_name: jyt0532_prod
  search_only_api_key: 66f08de38e8558a80afd764c6d59f028
